### ISSUE TITLE
App will contain the proprietary GMS library

### ISSUE THREAD

**Issue by mimi89999** [copperhead/Noise#4]
Not sure what you want to do and if that will be an issue, but Noise contains the proprietary GMS library. In my understanding features like location won't work anyway without gapps, so I would suggest removing all of that like in LS. If they are kept, the app won't be 100% free...

**Comment by thestinger** [comment]
I'm not sure if I want to remove it yet. I'd like to keep differences from the official Signal builds to a minimum. I'm not yet sure if I want to do a little bit more than making a temporary solution to be replaced by using official Signal builds ASAP. I need to think about it.

I agree with you that Conversations + OMEMO is the way to go and our documentation says as much: https://copperhead.co/android/docs/usage_guide#messaging. This exists so that I don't need to keep answering questions and hearing complaints about Signal, Google Play, microG, etc. So I'm not particularly interested in actually improving this app, only providing the most minimal set of changes that can work.

On the other hand, if many people end up using this on CopperheadOS, that creates an incentive to improve it beyond the minimal set of changes (hardened build, removing that proprietary library, etc.).

**Comment by thestinger** [comment]
The GMS library is also included in our Chromium builds, and I haven't yet decided how to deal with it there either. I don't particularly care about it from a security point of view. Java code is barely any harder to audit when you only have unobfuscated bytecode, so it doesn't really matter as a security issue. It's clear that the library isn't a backdoor. It even has signature checks, so it can't be tricked into using anything but Google's official Play Services and AFAIK it's not going to run as an unprivileged app anyway.

**Comment by legovini** [comment]
Anyway I modified Noise removing all the GMS related stuff (including the "send location" stuff, unfortunately). It seems to be working. I also tried it with a custom Signal-Server and PushServer installed on my laptop, it (mostly) works! It's not easy to setup due to the lack of documentation, incomplete sample configuration files, and so on, but it's definitely doable. I didn't really configure GCM and APN in the PushServer, as I was only interested in using websockets. Anyway it shouldn't be too difficult to remove the dependency of Signal-Server on PushServer.

I personally dream of an independent, Google-independent, federation-friendly network of Signal servers. I know that "everybody is on Signal", but in order for an alternative to exist somebody has to try. I would surly publish my personal efforts, but I'm worried by the cost of the registration SMS messages. We will see...

**Comment by thestinger** [comment]
How much do the SMS messages cost? I wouldn't be surprised if we could get that for free, similar to how all of our hosting is free. Never underestimate the willingness of companies to give out free stuff to promote themselves.

**Comment by craftyguy** [comment]
If you can figure out the carrier the user is using, many ( if not all) carriers support sending sms to a number in their service over email. For instance to send a sms to a tmobile user with phone number 1112223333, you can email 1112223333@tmomail.net. Here's one list I found of carrier sms email formats: http://www.emailtextmessages.com/

**Comment by legovini** [comment]
@craftyguy I know, there are also nice projects like http://textbelt.com/, but it's unreliable (compared with commercial services like Twilio), for many carriers the gateway is unknown, and there are usage limits. I don't think it could be a solution that works well enough for the average user.

**Comment by thestinger** [comment]
Since I want the need for this fork to go away, I don't want to remove this.
